Login close action added.
jdisho/Papr pull request #18
Opened 2018-03-23 11:13 UTC by DineshKachhot

Login close button action added.

2018-03-23 15:31 UTC, jdisho requested changes

2018-03-23 15:31 UTC, jdisho commented on Papr/Scenes/Login/LoginViewModel.swift
> +//            self.authenticate()
We can remove unnecessary comments.

2018-03-23 15:31 UTC, jdisho commented on Papr/Scenes/Login/LoginViewModel.swift
> +//            self.authenticate()
Why not returning just this: `self.sceneCoordinator.pop(animated: true)`? 
`sceneCoordinator.pop(animated: ...)` is an `Observable<Void>`

2018-03-23 15:31 UTC, jdisho commented on Papr/Scenes/Login/LoginViewModel.swift
> +    private func close() -> Observable<Void> {
... and we can remove this

2018-03-23 15:31 UTC, jdisho commented on Papr/Scenes/Login/LoginViewController.swift
> +
remove the unnecessary line

2018-03-28 10:35 UTC, DineshKachhot commented on Papr/Info.plist
> +				<string>papr://unsplash</string>
The general Url scheme.

2018-03-29 07:23 UTC, merged